# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bi59n6AqgCJAvqIfvieUiub3r_sr_uIH
"""

import gradio as gr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# Mock Data
# -----------------------------
kpis = {
    "Financial Exposure": "$45.2M",
    "Recovery Velocity": "$12.8M (MTD)",
    "Portfolio Risk": "68 / 100 (High)",
    "Audit Compliance": "14 Alerts (24h)"
}

dca_data = pd.DataFrame({
    "agency": ["Agency A", "Agency B", "Agency C", "Agency D"],
    "velocity": [85, 78, 55, 48],
    "sentiment": [80, 75, 45, 40],
    "size": [1200, 900, 700, 600]
})

weeks = ["Week 1", "Week 2", "Week 3", "Week 4"]
debt = [8, 10, 12, 15]
recovery = [6, 8, 9, 11]

alerts = [
    "🔴 Hardship Signal Detected – Collection Paused",
    "🟠 Negative Sentiment Drift – Flagged",
    "🟢 Compliance Check Passed",
    "🔴 Compliance Breach – Escalated"
]

# -----------------------------
# Plot Functions
# -----------------------------
def plot_dca_matrix():
    fig, ax = plt.subplots()
    ax.scatter(
        dca_data["velocity"],
        dca_data["sentiment"],
        s=dca_data["size"],
        alpha=0.6
    )
    for i, txt in enumerate(dca_data["agency"]):
        ax.annotate(txt, (dca_data["velocity"][i], dca_data["sentiment"][i]))
    ax.set_xlabel("Recovery Velocity")
    ax.set_ylabel("Avg Customer Sentiment")
    ax.set_title("DCA Efficiency & Ethics Matrix")
    return fig

def plot_forecast():
    fig, ax = plt.subplots()
    ax.bar(weeks, debt, label="Total Debt Maturing", alpha=0.6)
    ax.plot(weeks, recovery, marker="o", label="Predicted Recovery")
    ax.set_title("30-Day Cash Forecast")
    ax.legend()
    return fig

# -----------------------------
# Gradio UI
# -----------------------------
with gr.Blocks(title="Revenue Integrity Command Center") as demo:

    gr.Markdown("## 🌐 Global Revenue Integrity Command Center (Powered by AGENT-3)")

    # KPI Row
    with gr.Row():
        for k, v in kpis.items():
            gr.Markdown(f"""
            <div style="padding:12px;border-radius:8px;background:#f5f7fa">
                <b>{k}</b><br/>{v}
            </div>
            """)

    # Main Panels
    with gr.Row():

        # Left: Operational Insights
        with gr.Column(scale=2):
            gr.Markdown("### Operational Insights Panel")
            gr.Plot(plot_dca_matrix)
            gr.Plot(plot_forecast)

        # Right: Actions + Copilot
        with gr.Column(scale=1):
            gr.Markdown("### Real-Time Compliance Ticker")
            gr.Markdown("\n".join([f"- {a}" for a in alerts]))

            gr.Markdown("### Generative AI Co-Pilot")
            chat = gr.Chatbot(height=250)
            msg = gr.Textbox(placeholder="Ask why recovery dropped or simulate a strategy...")
            send = gr.Button("Send")

            def respond(m, h):
                h.append((m, "Analysis complete. Recovery drop linked to sentiment drift and slower DCA response time."))
                return h, ""

            send.click(respond, [msg, chat], [chat, msg])

demo.launch()